[env]
RUST_LOG = "actix_web=info,info"

[tasks.start_dev]
description = "Run serve in development mode"
command = "systemfd"
args = [
    "--no-pid",
    "-s", "http::8080",
    "--", "cargo", "watch", "-x", "run"
]